---
theme: jekyll-theme-slate
name: More Open-Science Initiatives from NRC
description: This site contains open-science initiatives followed by stephen.motty@nrc-cnrc.gc.ca
url: https://StephenMottyNRC.github.io
repository: https://github.com/StephenMottyNRC/StephenMottyNRC.github.io

exclude:
- .gitignore
- .jekyll-cache
- CNAME
- readme.md
