---
theme: jekyll-theme-slate
name: About Earth
title: About Earth
description: This site contains open-science initiatives about Earth
url: https://StephenMottyNRC.github.io
repository: https://github.com/StephenMottyNRC/StephenMottyNRC.github.io

exclude:
- .gitignore
- .jekyll-cache
- CNAME
- readme.md
