---
theme: jekyll-theme-slate
name: More Open-Science Initiatives from NRC
description: Deploy and test python algorithms using a sandboxed browser-based environment
url: https://StephenMottyNRC.github.io
repository: https://github.com/StephenMottyNRC/StephenMottyNRC.github.io

exclude:
- .gitignore
- .jekyll-cache
- CNAME
- readme.md
