---
theme: jekyll-theme-slate
name: Some Open-Science Initiatives
title: Some Open-Science Initiatives
description: This site contains open-science initiatives followed by stephen.motty@nrc-cnrc.gc.ca
url: https://StephenMottyNRC.github.io
repository: https://github.com/StephenMottyNRC/StephenMottyNRC.github.io

exclude:
- .gitignore
- .jekyll-cache
- CNAME
- readme.md
